---
- name: Install Day One via Mac App Store
  command: mas install "{{ item.id }}"
  args:
    creates: /Applications/{{ item.name }}.app
  with_items:
    - { id: 1055511498, name: "Day One" }
  when: ansible_os_family == "Darwin"
